name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s

      # - uses: convictional/trigger-workflow-and-wait@v1.3.0
      #   with:
      #     owner: idealo
      #     repo: ids-assets
      #     github_token: ${{ secrets.GH_ACCESS_TOKEN }}
      #     workflow_file_name: deploy-to-akamai.yml

      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN_ACTION }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'idealo',
              repo: 'ids-assets',
              workflow_id: 'deploy-to-akamai.yml',
              ref: 'main'
            })

      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s